Metadata window width
FelipeDefensor/TiLiA pull request #110
Opened 2024-05-28 16:37 UTC by azfoo

Closes #109.

2024-05-28 19:36 UTC, FelipeDefensor requested changes

2024-05-28 19:36 UTC, FelipeDefensor commented on tilia/settings.py
> +    },
We already have a "media_metadata" section, right below. Could we use that?

2024-05-28 19:36 UTC, FelipeDefensor commented on tilia/ui/windows/metadata.py
> +        self.setFixedWidth(settings.get("metadata", "window-width"))
This is good, but if there's no reason not to we should go with `self.resize(settings.get("metadata", "window-width"), self.height())` to keep the window resizable.

2024-05-28 20:42 UTC, azfoo commented on tilia/settings.py
> +    },
Good call

2024-05-28 21:20 UTC, azfoo commented on tilia/ui/windows/metadata.py
> +        self.setFixedWidth(settings.get("metadata", "window-width"))
Fixed Width:
![image](https://github.com/FelipeDefensor/TiLiA/assets/45888544/6ad554a9-9367-41b9-837c-1cd0aae18e1b)

Regular Resize:
![image](https://github.com/FelipeDefensor/TiLiA/assets/45888544/141d77dd-6406-4fc1-9ec8-9c0c9f02a24f)

Word wrapping is not very clever - someone with a silly file name could still accidentally make the window very long. But if that's compromisable, I agree that regular resizing provides more flexibility.

2024-05-28 21:36 UTC, FelipeDefensor commented on tilia/ui/windows/metadata.py
> +        self.setFixedWidth(settings.get("metadata", "window-width"))
Oh, I see. I still slightly prefer the resize option. In the future, we could add some processing to the string to handle those silly cases.

2024-05-29 11:14 UTC, FelipeDefensor approved these changes

2024-05-29 11:14 UTC, merged