Fix Inspector again
FelipeDefensor/TiLiA pull request #122
Opened 2024-06-01 00:24 UTC by azfoo

closes #119

2024-06-03 16:18 UTC, FelipeDefensor requested changes

2024-06-03 16:18 UTC, FelipeDefensor commented on tilia/ui/windows/inspect.py
> +        self.setUpdatesEnabled(False)
Is this supposed to prevent flickering when selecting elements? If so, this is a nice find and should come in handy in other places. It doesn't work for me, however (see video below).


https://github.com/FelipeDefensor/TiLiA/assets/87732202/798dce27-c769-4cf5-9ee2-58793ff5b5a0

2024-06-03 16:18 UTC, FelipeDefensor commented on tilia/ui/windows/inspect.py
> +        self.empty_label = QLabel("No element selected.")
Let's make the font a bit bigger and centralize this. The widget looks too empty as it is.

![inspector-no-element-selected](https://github.com/FelipeDefensor/TiLiA/assets/87732202/93f8d1ce-8116-45bd-9b5b-6aee407cb9b6)

2024-06-04 13:06 UTC, azfoo commented on tilia/ui/windows/inspect.py
> +        self.setUpdatesEnabled(False)
It doesn't work as well as I hoped, but it does flicker a little less.

2024-06-04 13:10 UTC, azfoo commented on tilia/ui/windows/inspect.py
> +        self.empty_label = QLabel("No element selected.")
Not too sure about the center align. See latest push.

2024-06-04 19:34 UTC, FelipeDefensor commented
Will take a look at the changes once I finish working on the PDF timeline. In the meantime, I found this:

https://github.com/FelipeDefensor/TiLiA/assets/87732202/3848b1c5-ad38-4953-962d-d0155201712a

2024-06-04 20:14 UTC, azfoo commented
> There's an empty space below the PDF inspector if we first open the inspector while it is selected.

I can't tell for sure, but it could be a branch thing. 
There is a notable gap after the last item on the table even on the latest update but I don't see anything that could be causing it.

2024-06-05 11:20 UTC, FelipeDefensor commented
> > There's an empty space below the PDF inspector if we first open the inspector while it is selected.
> 
> I can't tell for sure, but it could be a branch thing. There is a notable gap after the last item on the table even on the latest update but I don't see anything that could be causing it.

It's a branch thing, sorry. I was (obviously) using the pdf timeline branch when I made the video. I do just get the small gap when selecting beat on beat timelines.

2024-06-05 11:35 UTC, FelipeDefensor commented on tilia/ui/windows/inspect.py
> +        self.empty_label = QLabel("No element selected.")
We should also center it vertically, that will look much better. The problem is that gap in the bottom, once again. I don't want to waste a lot of time here, but I think we should try to remove that, if only to get this looking better. I also think we should go for bold instead of italic and use a more muted color.

We could sidestep this using the pevious strategy of disabling the widgets if there are no elements selected. I think that looks way better than the "No element selected" ever could. Could you perhaps check if the selected stack is empty and if so trigger a disable instead of a clear?

2024-06-05 11:38 UTC, FelipeDefensor commented on tilia/ui/windows/inspect.py
> +        self.setUpdatesEnabled(False)
That's the problem with rebuilding the widget from scratch on every new select/deselect. That may have been why I choose to repopulate it instead, I can't quite remember. Anyways, the flicker is better than the mounting dead space on the bottom.

2024-06-05 17:21 UTC, azfoo commented on tilia/ui/windows/inspect.py
> +        self.empty_label = QLabel("No element selected.")
Should be fixed now

2024-06-05 20:33 UTC, FelipeDefensor approved these changes
The stacked widget was a good solution. +1 for also improving the separator.

2024-06-05 20:37 UTC, FelipeDefensor commented
@azfoo this is approved. I have been rebasing and merging your PRs myself after approval, but I like the idea of the author doing that better. It gives a last chance to make any changes that might have occured to her between the review request and the approval. Let's start doing that with this PR, ok?

Don't forget that we are on the rebase team, so choose "Rebase and merge" instead of "Create a merge commit".

2024-06-05 21:33 UTC, merged

2024-06-05 21:34 UTC, azfoo commented
I think I did that right...
Will do the rebasing and merging myself in the future after your review approval.