Create Oscillogram Timeline
FelipeDefensor/TiLiA pull request #94
Opened 2024-05-10 16:08 UTC by azfoo

closes #93: created audio image timeline

2024-05-10 20:21 UTC, FelipeDefensor commented
Ok, I glanced at it, and you really seem to have found your way around the codebase. Bravo!

Unfortunately, I'm getting a bug right away (which is a shame because I'm really excited to see this working). When I try to load a media (local or YouTube) the duration in the toolbar (and I imagine in other parts of the software) is not updated, I still get a 0:00.0/0:00.0. Probably because of that, I'm unable to create any timelines, since TiLiA checks for `duration != 0` to see if a media is loaded and having a media loaded is a requirement for creating a timeline.

2024-05-10 20:52 UTC, azfoo commented
Oh dear. I don't think this iteration of the timeline touches anything that deals with loading and unloading media. The timeline has to be manually added after media is loaded. Any clue on how to reproduce the error?

2024-05-10 21:04 UTC, FelipeDefensor commented
Ok, so now I noticed this error message:

> QtWarningMsg: No QtMultimedia backends found. Only QMediaDevices, QAudioDevice, QSoundEffect, QAudioSink, and QAudioSource are available.
> QtWarningMsg: Failed to initialize QMediaPlayer "Not available"

2024-05-10 21:34 UTC, FelipeDefensor commented
Ok, so I upgraded to PyQt 6.7 on the upstream repo (i.e. the "original", not your fork) and was able to reproduce the bug, so this is most likely a PyQt issue. I'm having trouble downgrading though, so I'm still unable to run your code.

2024-05-10 22:05 UTC, azfoo commented
So I managed to reproduce the error in a virtual environment, with only the packages from `requirements.txt`. Could it be the missing ffmpeg that is causing this to happen?

2024-05-10 22:38 UTC, FelipeDefensor commented
Good call, this does seem to be ffmpeg related. If we set the environment variable `QT_MEDIA_BACKEND` to `windows`, the media loads fine (the default value is `ffmpeg`). As far as I know, an ffmpeg executable is supposed to be bundled with PyQt, so this is still weird.

2024-05-10 22:40 UTC, FelipeDefensor commented
I'm getting a blank oscillogram, though.

![image](https://github.com/FelipeDefensor/TiLiA/assets/87732202/cf55639e-3897-4c09-8811-c7fb126ccef3)

I wonder if that's also ffmpeg related. Are we relying on ffmpeg for the oscillogram?

2024-05-10 22:54 UTC, azfoo commented
Interesting... The image is created using pydub which relies on ffmpeg (the documentation suggests on for exporting audio, but I suspect reading audio would require it too). 

Could you show the terminal output?

2024-05-10 23:00 UTC, FelipeDefensor commented
Yeah, I think it relies on ffmpeg for doing what we want. I downloaded the ffmpeg binaries and added then to `PATH` and now the timeline is working.

![image](https://github.com/FelipeDefensor/TiLiA/assets/87732202/cd0ee211-16f2-4ee6-9d46-dbed6453035b)

2024-05-10 23:00 UTC, FelipeDefensor commented
It looks great, btw.

2024-05-10 23:06 UTC, FelipeDefensor commented
Ok, so I got the first real bug, I think. When I click and drag the oscillogram bars, I get an exception like this:

```
Traceback (most recent call last):
  File "C:\Users\Felipe\dev\tilia-desktop-azfoo\tilia\ui\timelines\view.py", line 86, in mouseMoveEvent
    post(Post.TIMELINE_VIEW_LEFT_BUTTON_DRAG, event.pos().x(), event.pos().y())
  File "C:\Users\Felipe\dev\tilia-desktop-azfoo\tilia\requests\post.py", line 221, in post
    callback(*args, **kwargs)
  File "C:\Users\Felipe\dev\tilia-desktop-azfoo\tilia\ui\timelines\drag.py", line 38, in on_mouse_drag
    self.after_each(dragged_to)
  File "C:\Users\Felipe\dev\tilia-desktop-azfoo\tilia\ui\timelines\oscillogram\element.py", line 109, in after_each_drag
    self.set_data("time", get_time_by_x(drag_x))
  File "C:\Users\Felipe\dev\tilia-desktop-azfoo\tilia\ui\timelines\base\element.py", line 53, in set_data
    self.timeline_ui.set_component_data(self.id, attr, value)
  File "C:\Users\Felipe\dev\tilia-desktop-azfoo\tilia\ui\timelines\base\timeline.py", line 194, in set_component_data
    self.timeline.set_component_data(id, attr, value)
  File "C:\Users\Felipe\dev\tilia-desktop-azfoo\tilia\timelines\base\timeline.py", line 165, in set_component_data
    return self.component_manager.set_component_data(id, attr, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\dev\tilia-desktop-azfoo\tilia\timelines\base\timeline.py", line 245, in set_component_data
    value, success = self.get_component(id).set_data(attr, value)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\dev\tilia-desktop-azfoo\tilia\timelines\base\component.py", line 50, in set_data
    if not self.validate_set_data(attr, value):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\dev\tilia-desktop-azfoo\tilia\timelines\base\component.py", line 39, in validate_set_data
    raise SetComponentDataError(
tilia.exceptions.SetComponentDataError: Component 'Oscillogram-2514084572304' has no attribute named 'time'. Can't set to '38.13435655253836'.
```

I'm guessing you partially implemented dragging unknowingly, so TiLiA is trying to set the `time`property of the oscillogram component when I click and drag. There seems to be no such property, though.

2024-05-10 23:10 UTC, FelipeDefensor commented
Second thing, changing the timeline's height is not working properly. Instead of resizing the graph, the graph is getting cropped.

![image](https://github.com/FelipeDefensor/TiLiA/assets/87732202/63944fda-265e-47ac-8075-8b7589289259)

You probably need to reimplement `TimelineUI.update_height` to fix that.

Also, the default height of 240 is excessive. Remember that there will be several other timelines timelines on-screen. I suggest we try out something like 80, to see how it looks.

2024-05-10 23:12 UTC, FelipeDefensor commented
So, I think we're back on track. I'll do a more detailed review over the weekend or early next week. After we finish implementing this timeline, I think that ensuring that ffmpeg is bundled properly with TiLiA or installed on-demand has become a top priority.

2024-05-11 10:36 UTC, azfoo commented
Thanks for identifying those issues! I have fixed both bugs with the latest commits. 
Let me know if you find anything else.

And yes, I agree with the need to sort out ffmpeg...

2024-05-11 14:22 UTC, FelipeDefensor requested changes
Like I said, great job overall. You've found your way around the codebase with minimal help and came up with a solution that looks great and is way more performant than what I have tried before. The idea of using the vertical bars instead of a full-fledged graph is clever and seems to be key for performance here. Importantly, they look just like a point-by-point plot when zoomed out and still capture the essential information when zoomed in.

The only major improvements to be done are on the OscillogramTimeline creation logic, as per the review.

There are also two other relevant things to deal with before merging this:
(1) We need some tests. Probably not many, as there is little interaction from the user with the timeline. Do you think you can handle creating those?
(2) I think the name of the timeline should be something more colloquial. I understand that oscillogram is the technical term, but I'm imagining a slightly less specialized user. What do you think about "audio wave timeline"?

2024-05-11 14:22 UTC, FelipeDefensor commented on tilia/ui/timelines/collection/requests/args.py
> +
Like I said while reviewing the OscillogramTimeline class, I think here is the place to check if a media is indeed loaded. Not that `_get_media_duration_valid_for_add_timeline` doesn't check for that, exactly, it only checks if `duration != 0`. When opening a file that has a media duration stored in its metadata but that is pointing to an inexisting media file (perhaps the user moved the file) there will be a non-zero duration but there will _not_ be a loaded media.

2024-05-11 14:22 UTC, FelipeDefensor commented on tilia/ui/timelines/oscillogram/element.py
> +        super().__init__(cursor_shape=Qt.CursorShape.PointingHandCursor)
I'm not sure if making the oscillogram elements selectable is a good idea. The only benefit I can see is that we can display the level and start/end times to the user, but that doesn't seem to be meaningful information for a vast majority. Also, making them not interactable might decrease maitenance effort down the road. What are your thoughts on this?

2024-05-11 14:22 UTC, FelipeDefensor commented on tilia/ui/timelines/oscillogram/request_handlers.py
> +                Post.TIMELINE_ELEMENT_PASTE: self.on_paste,
If we're not implementing these, I think we can just leave them out of this dictionary and delete the respective callbacks.

2024-05-11 14:23 UTC, FelipeDefensor commented
> Thanks for identifying those issues! I have fixed both bugs with the latest commits. Let me know if you find anything else.
> 
> And yes, I agree with the need to sort out ffmpeg...

Regarding this, I tested the new code and evrything works fine now.

2024-05-11 14:30 UTC, azfoo commented
> (1) We need some tests. Probably not many, as there is little interaction from the user with the timeline. Do you think you can handle creating those? 

- Will look into that

>(2) I think the name of the timeline should be something more colloquial. I understand that oscillogram is the technical term, but I'm imagining a slightly less specialized user. What do you think about "audio wave timeline"?

- That would work too. I was looking for a more concise name since I didn't think user would be looking too far into the code. But renaming it to that would work

2024-05-11 14:33 UTC, azfoo commented on tilia/timelines/oscillogram/components.py
> +        self.length = length
The duration determines the width of each bar, which should be equal across all bars. Also that passing the end time would mean having to work out the duration again, when it would already have been calculated in the previous step. But again, uniformity is good and I don't know if calculating and recalculating the numbers will affect performance much.

2024-05-11 14:34 UTC, azfoo commented on tilia/timelines/oscillogram/components.py
> +        self.level = level
I'll rename it `amplitude` if that's okay?

2024-05-11 14:38 UTC, azfoo commented on tilia/timelines/oscillogram/timeline.py
> +            return
Actually, I think that might cause a bug in a very specific scenario. I'll remove it...

2024-05-11 14:45 UTC, azfoo commented on tilia/timelines/oscillogram/timeline.py
> +            return
`pydub` cannot read YouTube files and will throw an error if the media path is set to a YouTube file. (That seems to be the only reason why the statement would fail.) I couldn't see any other way of easily checking if it is a readable file. 
I've kinda done a lazy job on it because I was looking to see if there was a way to read YouTube files, but I'll do `Post.DISPLAY_ERROR` for `CouldntDecodeError` instead.

2024-05-11 14:47 UTC, azfoo commented on tilia/timelines/oscillogram/timeline.py
> +                return
Again, I've just thought of a scenario in which this will not work as intended. Will be removing it.

2024-05-11 16:40 UTC, FelipeDefensor commented on tilia/timelines/oscillogram/components.py
> +        self.level = level
That's perfect.

2024-05-11 16:46 UTC, FelipeDefensor commented on tilia/timelines/oscillogram/timeline.py
> +            return
Even if you're not checking for the loaded media, I think the edge case I mentioned originally still applies.

2024-05-11 16:58 UTC, FelipeDefensor commented
> Have you tried pressing refresh after zooming in to the point of noticing bars?

Oh, I dindn't try that. So the "resolution" increases (up to a limit) if we do that, right?
 
> That would work too. I was looking for a more concise name since I didn't think user would be looking too far into the code. But renaming it to that would work

That's fair. But there are some important user contact points with the name, like the menu option for creating the timeline and references to it in the help docs. We could use the user-friendly name just in those points, but I think having two names would make coding harder.

We're going with `AudioWaveTimeline` then, right? Please change the class names accordingly. We will need a new name for the each vertical bar also, don't you think? Perhaps `AmplitudeMarker` or `WaveMarker`? Not sure I like those, though.

2024-05-11 17:12 UTC, azfoo commented
> Oh, I dindn't try that. So the "resolution" increases (up to a limit) if we do that, right?

Yes. The only point which it would be very very necessary is probably when you have a long file with short quiet parts that disappear with the original slices

> We're going with `AudioWaveTimeline` then, right? Please change the class names accordingly. We will need a new name for the each vertical bar also, don't you think? Perhaps `AmplitudeMarker` or `WaveMarker`? Not sure I like those, though.

Will do. Perhaps `SoundBar` or `AmplitudeBar`?

2024-05-11 17:33 UTC, FelipeDefensor commented
> Will do. Perhaps `SoundBar` or `AmplitudeBar`?

I like `AmplitudeBar`. How do you like `SoundChunk`?

2024-05-14 15:20 UTC, azfoo commented
> I like `AmplitudeBar`. How do you like `SoundChunk` or `AudioChunk`?

I think `AmplitudeBar` is probably more descriptive than  `SoundChunk` or `AudioChunk`

2024-05-14 15:42 UTC, FelipeDefensor commented
> > I like `AmplitudeBar`. How do you like `SoundChunk` or `AudioChunk`?
> 
> I think `AmplitudeBar` is probably more descriptive than `SoundChunk` or `AudioChunk`

Agree. Let's go with that.

2024-05-14 15:46 UTC, FelipeDefensor commented
On [03e1f55](https://github.com/FelipeDefensor/TiLiA/pull/94/commits/03e1f55d5494dd87b263594ad8dd369f5cc61517) I was able to trigger a refresh once new media loads. I will also do that for zooming. When that's done, I think the "Refresh" can be dispensed with. Correct?

2024-05-14 16:01 UTC, azfoo commented
> > Having looked at the code, I'm pretty sure we don't need the button and, therefore, this request. I'll make a commit soon with a fix.
> 
> On [03e1f55](https://github.com/FelipeDefensor/TiLiA/pull/94/commits/03e1f55d5494dd87b263594ad8dd369f5cc61517) I was able to trigger a refresh once new media loads. I will also do that for zooming. When that's done, I think the refresh button can be dispensed with. Correct?

Looks right!

2024-05-15 11:23 UTC, FelipeDefensor commented
> > > Having looked at the code, I'm pretty sure we don't need the button and, therefore, this request. I'll make a commit soon with a fix.
> > 
> > 
> > On [03e1f55](https://github.com/FelipeDefensor/TiLiA/pull/94/commits/03e1f55d5494dd87b263594ad8dd369f5cc61517) I was able to trigger a refresh once new media loads. I will also do that for zooming. When that's done, I think the refresh button can be dispensed with. Correct?
> 
> Looks right! Doing it with zoom levels would probably not work because of how long it takes to clear and redraw the bars. Zooming would start to lag as it is not an asynchronous process and redrawing would happen for every recorded step as opposed to only redrawing on the final zoom level change. Perhaps we ignore redrawing on the zoom levels instead? I don't think too much information will be lost without redrawing.

Yes, you are right. I did some testing and the performance hit is too big. I'm worried it's too big even in the case where there is no redrawing. Maybe we should reduce `max_div` to significantly less than 7500.

2024-05-16 19:07 UTC, FelipeDefensor requested changes
The setup for the tests looks complete, so we're ready to move on to writing tests sepcific for the audio wave timeline. Do you think you could do that?

Also, there's the issue with what class to rename to `AmplitudeBar`, see the comments.

2024-05-16 19:07 UTC, FelipeDefensor commented on tests/conftest.py
All the setup for the tests seems to be right. I imagine you are commiting the actual tests later.

2024-05-16 19:08 UTC, azfoo commented
Update: I thought it would be better if the timeline gets deleted if there isn't any relevant media to display. Deleting it would remove clutter on the UI, as opposed to leaving it on and not showing anything at all. This will break existing tests because the timeline removes itself as the tests do not actually provide any media.

2024-05-16 19:23 UTC, FelipeDefensor commented
> Update: I thought it would be better if the timeline gets deleted if there isn't any relevant media to display. Deleting it would remove clutter on the UI, as opposed to leaving it on and not showing anything at all. This will break existing tests because the timeline removes itself as the tests do not actually provide any media.

That seems sensible, but I have feeling that it will be hard pull off. Regarding the problem you ran into, you could exclude the timeline from those tests, I would have no problem with that.

But consider the case where we're changing from one media to another (which is rare, I reckon). First, the current media gets unloaded. A `Post.PLAYER_MEDIA_UNLOADED` gets fired. The audio wave timeline receives it and gets deleted. Right after, a new media gets loaded, but there's no audio wave timeline to refresh anymore.

What I feel could work is _hiding_ the timeline if there's no media available. Also, we could draw a bunch of tiny centered bars, as if the audio was silent, I would guess that's the simpler solution.

2024-05-16 19:26 UTC, azfoo commented
I seem to have been able to delete the timeline successfully. I thought hiding the timeline might cause the user to try and make more of them, so deleting them might be better.

2024-05-16 19:28 UTC, FelipeDefensor commented
Here's a Beethoven sonata zoomed in to display a pretty large main theme. It should be very rare that users would find zooming in more than this useful.

![image](https://github.com/FelipeDefensor/TiLiA/assets/87732202/b629fce3-1527-4213-8b58-b14abfbbdb2b)

The bar spacing looks acceptable, to me. I use 2500 as a fixed div number for this one. The performance when zooming is also acceptable. What do you think about that number?

One thing I will do to help is to increase the zoom factor, so each zoom triggered makes more of a visual difference and less zooming steps are required overall.

2024-05-16 19:30 UTC, FelipeDefensor commented
> I seem to have been able to delete the timeline successfully. I thought hiding the timeline might cause the user to try and make more of them, so deleting them might be better.

If you can handle the case where a different media gets loaded mentioned above, I have no problem with going this way.

2024-05-19 11:05 UTC, FelipeDefensor commented
Those last three commits all look good to me.

2024-05-22 11:18 UTC, FelipeDefensor requested changes
Almost there. Tests seem fine and enough. There is just the matter of the `AudioWaveUI.get_inspector_dict` method. By what I can recall from the last review, the only thing that's left addressing is the naming of the `AmplitudeBar` and `AudioWaveUI` classes.

2024-05-22 11:18 UTC, FelipeDefensor commented on tilia/timelines/audiowave/timeline.py
> +        self.audio = self._get_audio()
Caching is a good idea here, indeed.

2024-05-22 11:18 UTC, FelipeDefensor commented on tilia/timelines/collection/collection.py
> +            ) == 0
Nice catch!

2024-05-22 11:18 UTC, FelipeDefensor commented on tilia/ui/timelines/audiowave/timeline.py
> +        }
Any special reason to do this here instead of in `AudioWaveUI.get_inspector_dict`? I fell like all this could be done there, and then we would be consistent with the pattern seen in the analogous classes.

2024-05-23 23:04 UTC, FelipeDefensor approved these changes

2024-05-23 23:06 UTC, merged